#!/bin/sh

#### Recipe Variable Definitions ###############################################
JAIL_IP="${JAILS_LAN_SUBNET_C}.47"                                             # Optional:  ip address given to the jail (see FDo IP Policy)
RECIPE_PACKAGES="bind911"                                                      # Optional:  packages to install in the jail
RECIPE_REQUIRES_JAIL_RESTART="no"                                              # Mandatory: set to "yes" if the jail requires a restart after cooking
RECIPE_REQUIRES_NAT_RELOAD="no"                                                # Mandatory: set to "yes" if the hosts NAT (pf/ppp) requires a restart after cooking
START_JAIL_SERVICES="named"                                                    # Optional:  jail services started after cooking (in left to right order)
SIDES_FILESYSTEMS=""                                                           # Optional:  names of additional ZFS filesystems required for recipe
SIDES_MOUNTPOINTS=""                                                           # Optional:  mountpoints of additional ZFS filesystems required for recipe
DHCP_SERVER_JAIL_IP="${JAILS_LAN_SUBNET_C}.48"                                 #
################################################################################

prep_recipe ()
{
	PREP_SUCCESS="yes"
}

cook_recipe ()
{

	echo -e "\n${YELL}Next we need to install the recipe packages into the jail.${NRML}"
	echo -e "${YELL}Please accept when prompted...${NRML}\n"
	sleep 5

	# Install essential jail recipe packages from the recipe repo
	pkg -j ${JAIL_NAME} install ${RECIPE_PACKAGES}
	if [ ${?} -ne 0 ]
	then
		echo -e "\n${LRED}ERROR:${NRML} Installing of recipe packages failed.\n"
		RECIPE_SUCCESS="no"
		return
	fi

	# Update resolv.conf in all existing jails and future jails to use this caching dns server
	sed -i "" "s/^#nameserver FDO_DNS_CACHE_IP/nameserver ${JAIL_IP}/" configs/${HOST_NAME}/etc/resolv.conf.static
	sed -i "" "s/^#nameserver FDO_DNS_CACHE_IP/nameserver ${JAIL_IP}/" /jls/template/etc/resolv.conf
	for JAIL_NAME_IN_JAILS in `ls -1 /jls | cut -d/ -f1 | egrep -v "template"`
	do
		cp /jls/template/etc/resolv.conf /jls/${JAIL_NAME_IN_JAILS}/etc/resolv.conf
	done

	# Update bind global config with the jail IP
	sed -i "" "s/FDO_DNS_CACHE_IP/${JAIL_IP}/" configs/${JAIL_NAME}@${HOST_NAME}/usr/local/etc/namedb/named.conf

	# Determine if a dhcp server is running on the LAN and recommend changing it's domain-name-servers
	nmap ${DHCP_SERVER_JAIL_IP} -sU -p 67 | egrep "^67/udp.*open\|filtered.*dhcp" > /dev/null 2>&1
	if [ ${?} -eq 0 ]
	then
		echo -e "\n${ORNG}NOTICE:${NRML} It seems that a DHCP server is running on the LAN (local network).      "
		echo -e   "        It's recommended to change the 'domain-name-servers' to this jails'     "
		echo -e   "        IP address [${JAIL_IP}].                                                "
		echo -e   "        The DHCP server config file could be found at the following path in the "
		echo -e   "        'dhcp_server' recipe jail:                                              "
		echo -e   "        ${LBLU}/usr/local/etc/dhcpd.conf${NRML}                                 \n"

		pause_prompt 15
	fi

	# Get seasoning suggestion message from recipe.conf.
	SEASONING_SUGGESTION_MSG=`${UCL_CMD} get -f configs/${JAIL_NAME}@${HOST_NAME}${RECIPE_CONF_PATH} .seasoning_suggestion.message`

	# Echo the seasoning suggestion message to the terminal, expanding any variables.
	eval echo -e "\"\n${YELL}Seasoning suggestion:${NRML}\n${SEASONING_SUGGESTION}\n\""

	# Set the seasoning suggestion message in recipe.conf after expanding any variables.
	EXPANDED_SEASONING_SUGGESTION_MSG=`eval echo -e "\"${SEASONING_SUGGESTION}\""`
	${UCL_CMD} set -f configs/${JAIL_NAME}@${HOST_NAME}${RECIPE_CONF_PATH} .seasoning_suggestion.message "${EXPANDED_SEASONING_SUGGESTION_MSG}"

	pause_prompt 15

	# Mandatory: return code
	RECIPE_SUCCESS="yes"

}
