#!/bin/sh
#
#
# PROVIDE: fdo-notifierd
# REQUIRE: DAEMON
#
# Add the following lines to /etc/rc.conf to enable the fdo-notifierd system:
#
# fdo-notifierd_enable="YES"
#

. /etc/rc.subr

name="fdo-notifierd"
rcvar=${name}_enable

load_rc_config ${name}

command="/usr/local/bin/fdo-notifierd"
pidfile="/var/run/fdo-notifierd.pid"

start_precmd="fdo-notifierd_prestart"
stop_postcmd="fdo-notifierd_poststop"
start_cmd="fdo-notifierd_start"
stop_cmd="fdo-notifierd_stop"
restart_cmd="fdo-notifierd_restart"
status_cmd="fdo-notifierd_status"

fdo-notifierd_prestart()
{
    if [ ! -d /var/log/fdo-notifierd ]; then
        mkdir -p /var/log/fdo-notifierd
    fi
}

fdo-notifierd_start()
{
    if [ -f ${pidfile} ]; then
        echo "${name} is already running as pid `cat ${pidfile}`"
    else
        ${command} start
    fi
}

fdo-notifierd_stop()
{
    if [ ! -f ${pidfile} ]; then
        echo "${name} is not running"
    else
        ${command} stop
    fi
}

fdo-notifierd_restart()
{
    if [ ! -f ${pidfile} ]; then
        echo "${name} is not running. To start it run: ${name} start"
    else
        ${command} restart
    fi
}

fdo-notifierd_status()
{
    if [ -f ${pidfile} ]; then
    echo "${name} is running as pid `cat ${pidfile}`"
    else
        echo "${name} is not running"
    fi
}

fdo-notifierd_poststop()
{
}


load_rc_config ${name}
run_rc_command "$1"
