#!/bin/sh
#
#
# PROVIDE: fdo_notifierd
# REQUIRE: DAEMON
#
# Add the following lines to /etc/rc.conf to enable the fdo_notifierd system:
#
# fdo_notifierd_enable="YES"
#

. /etc/rc.subr

name="fdo_notifierd"
rcvar=${name}_enable

load_rc_config ${name}
: ${fdo_notifierd_enable="NO"}

command="/usr/local/bin/fdo_notifierd"
pidfile="/var/run/fdo_notifierd.pid"

start_precmd="fdo_notifierd_prestart"
stop_postcmd="fdo_notifierd_poststop"
start_cmd="fdo_notifierd_start"
stop_cmd="fdo_notifierd_stop"
restart_cmd="fdo_notifierd_restart"
status_cmd="fdo_notifierd_status"

fdo_notifierd_prestart()
{
    if [ ! -d /var/log/fdo_notifierd ]; then
        mkdir -p /var/log/fdo_notifierd
    fi
}

fdo_notifierd_start()
{
    if [ -f ${pidfile} ]; then
        echo "${name} is already running as pid `cat ${pidfile}`"
    else
        ${command} start
    fi
}

fdo_notifierd_stop()
{
    if [ ! -f ${pidfile} ]; then
        echo "${name} is not running"
    else
        ${command} stop
    fi
}

fdo_notifierd_restart()
{
    if [ ! -f ${pidfile} ]; then
        echo "${name} is not running. To start it run: ${name} start"
    else
        ${command} restart
    fi
}

fdo_notifierd_status()
{
    if [ -f ${pidfile} ]; then
    echo "${name} is running as pid `cat ${pidfile}`"
    else
        echo "${name} is not running"
    fi
}

fdo_notifierd_poststop()
{
}

run_rc_command "$1"
