#!/bin/sh

SHORT_ORG_NAME=${1}
USERID=${2}

WEBDAV_ROOT_FS=`cat /usr/local/etc/fdo/webdav_root_fs.conf`

if [ $# -ne 2 ]
then
  echo ""
  echo "Usage:   ${0} SHORT_ORG_NAME USERID"
  echo "Example: ${0} ffs joe.bloggs"
  echo ""
  exit 1
fi

zfs get quota ${WEBDAV_ROOT_FS}/${SHORT_ORG_NAME}/users/${USERID}

