#!/bin/sh

# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################

SCRIPT_NAME=`basename ${0}`
POOL="${1}"
FILESYSTEM_PATTERN="${2}"
NUM_MANDATORY_ARGS=2
RECURSE=""
SIMULATION_MODE="no"

TERM="xterm"
LRED="\033[1;31m"
LGRN="\033[1;32m"
LBLU="\033[1;34m"
LCYN="\033[1;36m"
CYAN="\033[0;36m"
YELL="\033[1;33m"
ORNG="\033[0;33m"
GREY="\033[0;37m"
DGRY="\033[1;30m"
NRML="\033[0;00m"

CARRIAGE_RETURN="
"

##### COMMAND USAGE INFO #######################################################

usage ()
{
	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
	then
		return 1
	fi

	echo -e ""
	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
	echo -e ""
	echo -e "${YELL}Description:${NRML} destroy all filesystems from a given pool that match a given"
	echo -e "             pattern in their name."
	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} pool_to_destroy_from filesystem_pattern [--recursive ] [--simulate]${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} backup Accounts --recursive${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} backup \"Accounts/Reports\" --simulate${NRML}"
	echo -e ""
	echo -e "${YELL}Options:${NRML}"
	echo -e ""
	echo -e "${YELL}--recursive  Destroy the children of any matching filesystem.${NRML}"
	echo -e ""
	echo -e "${YELL}--simulate   Simulation mode. Will output the commands but not execute them.${NRML}"
	echo -e ""
}

##### PARSE ARGUMENTS ##########################################################

ARG_INDEX=1
for ARG in "${@}"
do
	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
	then
		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
		case ${OPTIONAL_ARG_NAME} in
			--recursive)
				RECURSE="-r"
				;;
			--simulate)
				SIMULATION_MODE="yes"
				;;
			*)
				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\n       Aborting.\n"
				usage
				exit 1
				;;
		esac
	fi

	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))

done


##### FUNCTIONS ################################################################

test_if_host ()
{
	procstat 0 > /dev/null 2>&1
	if [ ${?} -eq 0 ]
	then
		IS_HOST=yes
	else
		IS_HOST=no
	fi
}


##### SANITY TESTS #############################################################

if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
then
	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
	usage
	exit 1
fi

test_if_host

if [ "${IS_HOST}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
	exit 1
fi

POOL_ATTRIBUTES=`zpool get -H all ${POOL} 2> /dev/null`
if [ ${?} -ne 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported.\n       Aborting.\n"
	exit 1
fi

POOL_HEALTH=`zpool get -H health ${POOL} | awk '{print $3}' 2> /dev/null`
if [ "${POOL_HEALTH}" != "ONLINE" ]
then
	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy.\n       Aborting.\n"
	exit 1
fi

if [ -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ]
then
	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backup running for '${POOL}'!\n       Aborting.\n"
	exit 1
fi

pgrep -fl "fdo-backupz-repair-state" > /dev/null 2>&1
if [ ${?} -eq 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backup repair operation running!\n       Aborting.\n"
	exit 1
fi

pgrep -fl "fdo-backupz-thin-snapshots" > /dev/null 2>&1
if [ ${?} -eq 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} There appears to be a thin-snapshots operation running!\n       Aborting.\n"
	exit 1
fi


##### MAIN EXECUTION THREAD ####################################################

ERROR_COUNT=0

# Find and destroy all matching filesystems.
TO_DESTROY=`zfs list -H -t filesystem -r ${POOL} | awk '{print $1}' | grep "${FILESYSTEM_PATTERN}"`

if [ "${SIMULATION_MODE}" = "yes" ]
then
	echo -e "\n${YELL}   --- SIMULATION MODE ---   ${NRML}\n"
	for i in ${TO_DESTROY}
	do
		echo -e "zfs destroy ${RECURSE} -v ${i}"
	done
else
	echo -e "\n${YELL}Destroying filesystems...${NRML}\n"
	for i in ${TO_DESTROY}
	do
		zfs destroy -v ${RECURSE} ${i}
		if [ ${?} -ne 0 ]
		then
			ERROR_COUNT=$(( ${ERROR_COUNT} + 1 ))
		fi
	done
fi

if [ ${ERROR_COUNT} -gt 0 ]
then
	exit 2
fi

################################################################################
