#!/bin/sh

# Copyright (c) 2018 Euan Thoms <euan@potensol.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################

SCRIPT_NAME=`basename ${0}`
RULE_NAME="${1}"
NUM_MANDATORY_ARGS=1
IS_INTERACTIVE="yes"
FDO_SERVER_SCRIPT=${FDO_SERVER_SCRIPT:-"fdo-server"}
UCL_CMD="/usr/local/bin/uclcmd"
FDO_CONFIG_ROOT=${FDO_CONFIG_ROOT:-"/usr/local/etc/fdo"}
HOST_CONF_PATH=${HOST_CONF_PATH:-"${FDO_CONFIG_ROOT}/host.conf"}
PF_CONF_PATH=${PF_CONF_PATH:-"/etc/pf.conf"}
REPO_NAME=${REPO_NAME:-"fdo-server"}

TERM="xterm"
LRED="\033[1;31m"
LGRN="\033[1;32m"
LBLU="\033[1;34m"
LCYN="\033[1;36m"
CYAN="\033[0;36m"
YELL="\033[1;33m"
ORNG="\033[0;33m"
GREY="\033[0;37m"
DGRY="\033[1;30m"
NRML="\033[0;00m"

CARRIAGE_RETURN="
"

##### COMMAND USAGE INFO #######################################################

usage ()
{
	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
	then
		return 1
	fi

	echo -e ""
	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
	echo -e ""
	echo -e "${YELL}Description:${NRML} Remove pf rules for port forwarding for this host."
	echo -e ""
	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} rule_name [--non-interactive]${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} cups_server${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} vnc_servers --non-interactive${NRML}"
	echo -e ""
	echo -e "${YELL}Options:${NRML}"
	echo -e "${YELL}         --non-interactive ; will not prompt or commit changes to the config repo.${NRML}"
	echo -e ""
}


##### PARSE ARGUMENTS ##########################################################

ARG_INDEX=1
for ARG in "${@}"
do
	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
	then
		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
		case ${OPTIONAL_ARG_NAME} in
			--non-interactive)
				IS_INTERACTIVE="no"
				;;
			*)
				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\n       Aborting.\n"
				usage
				exit 1
				;;
		esac
	fi

	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))

done


##### FUNCTIONS ################################################################

# source readee function.
. /usr/local/bin/fdo-readee

question_yes_no ()
{
	while true
	do
		echo -e "${LCYN}${1}${NRML}"
		readee -p "${LCYN}(yes|no): ${NRML}" ANSWER
		if [ "${ANSWER}" = "yes" ] || [ "${ANSWER}" = "no" ]
		then
			break
		fi
		echo ""
	done
}

test_valid_rule_name ()
{
	TEST_CASE="${1}"

	VALID_RULE_NAME="yes"

	if [ ${TEST_CASE} = "" ]
	then
		VALID_RULE_NAME="no"
		return 1
	fi

	IS_SYNTAX_OK=`echo "${TEST_CASE}" | sed -r "s/^[a-zA-Z0-9]+(_[a-zA-Z0-9]+[a-zA-Z0-9]*)*//" | wc -L`
	if [ ${IS_SYNTAX_OK}  -ne 0 ]
	then
		VALID_RULE_NAME="no"
		return 2
	fi

}

test_if_host ()
{
	procstat 0 > /dev/null 2>&1
	if [ ${?} -eq 0 ]
	then
		IS_HOST=yes
	else
		IS_HOST=no
	fi
}

backup_file ()
{
	FILE_PATH="${1}"
	CHANGE_AGENT="${2}"
	if [ -f "${FILE_PATH}" ]
	then
		BACKUP_FILE_PATH="${FILE_PATH}.backup.${CHANGE_AGENT}"
		cp "${FILE_PATH}" "${BACKUP_FILE_PATH}" 2> /dev/null
		if [ ${?} -ne 0 ]
		then
			echo -e "\n${LRED}ERROR:${NRML} Failed to backup file '${ORNG}${FILE_PATH}${NRML}'!\n"
			BACKUP_FILE_PATH=""
			return 2
		fi
	else
		echo -e "\n${LRED}ERROR:${NRML} File '${ORNG}${FILE_PATH}${NRML}' does not exist!\n       Unable to backup.\n"
		BACKUP_FILE_PATH=""
		return 1
	fi

	return 0
}

restore_file ()
{
	FILE_PATH=${1}
	CHANGE_AGENT="${2}"

	if [ -f "${FILE_PATH}" ] && [ -f "${FILE_PATH}.backup.${CHANGE_AGENT}" ]
	then
		diff -q "${FILE_PATH}" "${FILE_PATH}.backup.${CHANGE_AGENT}" > /dev/null 2>&1
		if [ ${?} -ne 0 ]
		then
			# File and backup differ, replace the file content from the backup copy.
			cat "${FILE_PATH}.backup.${CHANGE_AGENT}" > "${FILE_PATH}"
			if [ ${?} -ne 0 ]
			then
				return 2
			fi
		fi
		# Remove the backup.
		rm "${FILE_PATH}.backup.${CHANGE_AGENT}"
		if [ ${?} -ne 0 ]
		then
			return 2
		fi
	else
		# File has been removed, so move backup to file path.
		mv "${FILE_PATH}.backup.${CHANGE_AGENT}" "${FILE_PATH}"
		if [ ${?} -ne 0 ]
		then
			return 2
		fi
	fi

	return 0

}

undo_backup_file ()
{
	FILE_PATH=${1}
	CHANGE_AGENT="${2}"

	if [ -f "${FILE_PATH}.backup.${CHANGE_AGENT}" ]
	then
		# Remove the backup.
		rm "${FILE_PATH}.backup.${CHANGE_AGENT}"
		if [ ${?} -ne 0 ]
		then
			return 2
		fi
	fi

	return 0

}

undo_remove_rule ()
{
	ERROR_COUNT=0

	echo -e "\n${ORNG}Undoing remove port forward rule process...${NRML}\n"

	# Restore existing system config files.
    if [ ${REMOVE_RULE_SYSTEM_MODIFIED} = true ]
    then
		# Restore pf.conf config file.
		restore_file ${PF_CONF_PATH} ${SCRIPT_NAME}
		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
	fi

	# Reload pf service.
    if [ ${REMOVE_RULE_SERVICE_RELOADED} = true ]
    then
		service pf reload > /dev/null
		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
	fi

	# Undo repo modifications.
    if [ ${REMOVE_RULE_REPO_MODIFIED} = true ]
    then
        # Roll back local repo to last good commit (!!!DANGEROUS!!!).
        if [ "${COMMIT_BEFORE_REMOVE_RULE}" != "" ]
        then
            git reset --hard ${COMMIT_BEFORE_REMOVE_RULE}
            ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
            git clean -f -d
            ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
        fi
    fi

	if [ ${ERROR_COUNT} -ne 0 ]
	then
		echo -e "\n${LRED}ERROR:${NRML} An error occurred whilst trying to undo remove port forward rule!\n"
	else
		echo -e ""
	fi
}

##### SANITY TESTS #############################################################

if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
then
	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
	usage
	exit 1
fi

# Check we are running with root privileges.
if [ `id -u` -ne 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} This command must be run with root (super-user) privileges!\n       Aborting.\n"
	exit 1
fi

test_if_host

if [ "${IS_HOST}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
	exit 1
fi

# Check that the host.conf file exists.
if [ ! -e "${HOST_CONF_PATH}" ]
then
	echo -e "\n${LRED}ERROR:${NRML} The host config file \n       '${ORNG}${HOST_CONF_PATH}${NRML}'"
	echo -e "       appears to be missing.\n       Aborting.\n"
	exit 1
fi

# Check that the host.conf file is accessible.
TEST_UCL=`${UCL_CMD} get -u -f ${HOST_CONF_PATH} .general 2>&1`
if [ ${?} -ne 0 ] || [ "${TEST_UCL}" = "null" ] || [ "${TEST_UCL}" = "" ]
then
	echo -e "\n${LRED}ERROR:${NRML} Failed to access the config file '${HOST_CONF_PATH}'!\n       Aborting.\n"
	exit 2
fi

# Check that the pf.conf config file exists.
if [ ! -f ${PF_CONF_PATH} ]
then
	echo -e "\n${LRED}ERROR:${NRML} The pf config file '${PF_CONF_PATH}' does not exist!\n       Aborting.\n"
	usage
	exit 1
fi

# Check for unsaved registered host config files.
echo -e "\n${YELL}Now we need to check if there are any unsaved changes to this hosts registered\nconfig files...${NRML}\n"
${FDO_SERVER_SCRIPT} check-configs --script > /dev/null 2>&1
if [ ${?} -gt 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} One or more host config files are not updated in the repo."
	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} check-configs${NRML}' subcommand to see what's out-of-date."
	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} update-config${NRML}' subcommannd to keep the repo up-to-date.\n       Aborting.\n"
	exit 1
fi

# Test if rule_name is valid.
test_valid_rule_name "${RULE_NAME}"
if [ "${VALID_RULE_NAME}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} Rule name invalid!\n"
	exit 1
fi

# Test if rule_name exists.
cat ${PF_CONF_PATH} | egrep "${RULE_NAME}_ip =" > /dev/null 2>&1
if [ ${?} -ne 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} Rule name '${RULE_NAME}' does not exist!\n"
	exit 1
fi


##### MAIN EXECUTION THREAD ####################################################

trap 'undo_remove_rule ; exit 3' HUP INT QUIT KILL TERM

ERROR_COUNT=0

REMOVE_RULE_SERVICE_RELOADED=false
REMOVE_RULE_REPO_MODIFIED=false
REMOVE_RULE_SYSTEM_MODIFIED=false

# Move into local repo directory.
cd "/${REPO_NAME}"
if [ ${?} -ne 0 ]
then
    echo -e "\n${LRED}ERROR:${NRML} Unable to enter the repo directory; '${ORNG}/${REPO_NAME}${NRML}'!"
    return 2
fi

# Save git commit reference so we can roll back changes later.
COMMIT_BEFORE_REMOVE_RULE=`git log --format=format:%H -1`

# Backup pf.conf config file in case something goes wrong.
backup_file ${PF_CONF_PATH} ${SCRIPT_NAME}
ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))

REMOVE_RULE_SYSTEM_MODIFIED=true

# Remove all lines mentioning the specified rule_name.
sed -i "" "/${RULE_NAME}_ip/d" ${PF_CONF_PATH}
ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
sed -i "" "/${RULE_NAME}_tcp_ports/d" ${PF_CONF_PATH}
ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
sed -i "" "/${RULE_NAME}_udp_ports/d" ${PF_CONF_PATH}
ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))

if [ ${ERROR_COUNT} -ne 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} Something went wrong updating the configuration files!\n       Aborting.\n"
	undo_remove_rule
	exit 2
fi

if [ "${IS_INTERACTIVE}" = "yes" ]
then
	question_yes_no "\nWould you like to reload the pf service for changes to take effect?"
	if [ "${ANSWER}" = "yes" ]
	then
		REMOVE_RULE_SERVICE_RELOADED=true
	fi
else
	REMOVE_RULE_SERVICE_RELOADED=true
fi

if [ ${REMOVE_RULE_SERVICE_RELOADED} = true ]
then
	echo -e "\n${YELL}Reloading pf service...${NRML}\n"
	service pf reload > /dev/null
	if [ ${?} -eq 0 ]
	then
		echo -e "\n${LGRN}Successfully reloaded pf service!${NRML}\n"
	else
		echo -e "\n${LRED}Reload of pf service returned an error!${NRML}\n"
		undo_remove_rule
		exit 2
	fi
fi

# Update configuration in the local repo and if interactive mode then push to remote repo.
REMOVE_RULE_REPO_MODIFIED=true
if [ "${IS_INTERACTIVE}" = "yes" ]
then
	echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH} ...\n"
	CHANGE_MESSAGE="remove port forwarding rule '${RULE_NAME}' from pf config" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH}
	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
else
	echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH} ...\n"
	CHANGE_MESSAGE="remove port forwarding rule '${RULE_NAME}' from pf config" GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH}
	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
fi

if [ ${ERROR_COUNT} -gt 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} Something went wrong updating the config repo!\n       Aborting.\n"
	undo_remove_rule
	exit 2
fi

undo_backup_file ${PF_CONF_PATH} ${SCRIPT_NAME}

################################################################################
