#!/bin/sh

# Copyright (c) 2018 Euan Thoms <euan@potensol.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################

SCRIPT_NAME=`basename ${0}`
RULE_NAME="${1}"
NUM_MANDATORY_ARGS=1
IS_INTERACTIVE="yes"
IS_REPO_CONF=${IS_REPO_CONF:-"no"}
PF_CONF_PATH=${PF_CONF_PATH:-"/etc/pf.conf"}
FDO_SERVER_SCRIPT=${FDO_SERVER_SCRIPT:-"fdo-server"}

TERM="xterm"
LRED="\033[1;31m"
LGRN="\033[1;32m"
LBLU="\033[1;34m"
LCYN="\033[1;36m"
CYAN="\033[0;36m"
YELL="\033[1;33m"
ORNG="\033[0;33m"
GREY="\033[0;37m"
DGRY="\033[1;30m"
NRML="\033[0;00m"

CARRIAGE_RETURN="
"

##### COMMAND USAGE INFO #######################################################

usage ()
{
	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
	then
		return 1
	fi

	echo -e ""
	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
	echo -e ""
	echo -e "${YELL}Description:${NRML} Remove pf rules for port forwarding for this host."
	echo -e ""
	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} rule_name [--non-interactive]${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} cups_server${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} vnc_servers --non-interactive${NRML}"
	echo -e ""
	echo -e "${YELL}Options:${NRML}"
	echo -e "${YELL}         --non-interactive ; will not prompt or commit changes to the config repo.${NRML}"
	echo -e ""
}


##### PARSE ARGUMENTS ##########################################################

ARG_INDEX=1
for ARG in "${@}"
do
	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
	then
		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
		case ${OPTIONAL_ARG_NAME} in
			--non-interactive)
				IS_INTERACTIVE="no"
				;;
			*)
				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\n       Aborting.\n"
				usage
				exit 1
				;;
		esac
	fi

	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))

done


##### SANITY TESTS #############################################################

if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
then
	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
	usage
	exit 2
fi

if [ ! -f ${PF_CONF_PATH} ]
then
	echo -e "\n${LRED}ERROR:${NRML} The pf config file '${PF_CONF_PATH}' does not exist!\n       Aborting.\n"
	usage
	exit 3 
fi


##### FUNCTIONS ################################################################

question_yes_no ()
{
	while true
		do
		echo -e "${LCYN}${1} (yes/no): ${NRML}\c"
		read ANSWER
		if [ "${ANSWER}" = "yes" ] || [ "${ANSWER}" = "no" ]
		then
			break
		fi
		echo ""
	done
}

test_valid_rule_name ()
{
	TEST_CASE="${1}"

	VALID_RULE_NAME="yes"

	if [ ${TEST_CASE} = "" ]
	then
		VALID_RULE_NAME="no"
		return 1
	fi

	IS_SYNTAX_OK=`echo "${TEST_CASE}" | sed -r "s/^[a-z0-9]+(_[a-z0-9]+[a-z0-9]*)*//" | wc -L`
	if [ ${IS_SYNTAX_OK}  -ne 0 ]
	then
		VALID_RULE_NAME="no"
		return 2
	fi

}

################################################################################


##### MAIN EXECUTION THREAD ####################################################

ERROR_COUNT=0

# Test if rule_name is valid
test_valid_rule_name "${RULE_NAME}"
if [ "${VALID_RULE_NAME}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} Rule name invalid!\n"
	exit 4
fi

# Test if rule_name exists
cat ${PF_CONF_PATH} | egrep "${RULE_NAME}_ip =" > /dev/null 2>&1
if [ ${?} -ne 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} Rule name '${RULE_NAME}' does not exist!\n"
	exit 5
fi

# Remove all lines mentioning the specified rule_name
sed -i "" "/${RULE_NAME}_ip/d" ${PF_CONF_PATH}
sed -i "" "/${RULE_NAME}_tcp_ports/d" ${PF_CONF_PATH}
sed -i "" "/${RULE_NAME}_udp_ports/d" ${PF_CONF_PATH}


if [ "${IS_REPO_CONF}" = "no" ]
then
	# Update configuration in the local repo and if interactive mode then push to remote repo
	if [ "${IS_INTERACTIVE}" = "no" ]
	then
		echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH} ...\n"
		CHANGE_MESSAGE="remove port forwarding rule '${RULE_NAME}' from pf config" GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH}
	else
		question_yes_no "\nWould you like to update the repo with the config changes?"
		if [ "${ANSWER}" = "yes" ]
		then
			echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH} ...\n"
			CHANGE_MESSAGE="remove port forwarding rule '${RULE_NAME}' from pf config" ${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH}
		fi
	fi
fi

if [ ${ERROR_COUNT} -gt 0 ]
then
	exit 6
fi

################################################################################
