#!/bin/sh

USERNAME=${1}
HOST=${2}
LOCAL_DIR=${3}

while [ 1 ]
do
  echo ""
  echo "Start of loop"
  echo ""
  scp ${USERNAME}@${HOST}:~/100MB.file ${LOCAL_DIR} > /dev/null 2>&1
  sleep 20
  scp ${LOCAL_DIR}/100MB.file ${USERNAME}@192.168.10.1:~/ > /dev/null 2>&1
  sleep 20
done
