#!/bin/sh

# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################

SCRIPT_NAME=`basename ${0}`
USERNAME="${1}"
HOME_ZFS_NAME=`cat /usr/local/etc/fdo/hotdesk-home-zfs-name.conf`
NUM_MANDATORY_ARGS=1
FORCE_MODE="no"
DEFAULT_BACKUP_POOL="backup"
DATE_CMD=/bin/date
NOW=`${DATE_CMD} +%Y-%m-%d_%H-%M`

TERM="xterm"
LRED="\033[1;31m"
LGRN="\033[1;32m"
LBLU="\033[1;34m"
LCYN="\033[1;36m"
CYAN="\033[0;36m"
YELL="\033[1;33m"
ORNG="\033[0;33m"
GREY="\033[0;37m"
DGRY="\033[1;30m"
NRML="\033[0;00m"

CARRIAGE_RETURN="
"

##### COMMAND USAGE INFO #######################################################

usage ()
{
	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
	then
		return 1
	fi

	echo -e ""
	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
	echo -e ""
	echo -e "${YELL}Description:${NRML} Remove a hotdesk user from a host configured for"
	echo -e "             FDo NIS/NFS hotdesking."
	echo -e ""
	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} username [--force]${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} joe.bloggs${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} joe.bloggs --force${NRML}"
	echo -e ""
	echo -e "${YELL}Options:${NRML}"
	echo -e ""
	echo -e "${YELL}--force  Ignore errors and force all removal steps.${NRML}"
	echo -e ""
}


##### PARSE ARGUMENTS ##########################################################

ARG_INDEX=1
for ARG in "${@}"
do
	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
	then
		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
		case ${OPTIONAL_ARG_NAME} in
			--force)
				FORCE_MODE-"yes"
				;;
			*)
				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\n       Aborting.\n"
				usage
				exit 1
				;;
		esac
	fi

	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))

done


##### FUNCTIONS ################################################################

test_if_host ()
{
	procstat 0 > /dev/null 2>&1
	if [ ${?} -eq 0 ]
	then
		IS_HOST=yes
	else
		IS_HOST=no
	fi
}


##### SANITY TESTS #############################################################

if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
then
	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
	usage
	exit 1
fi

test_if_host

if [ "${IS_HOST}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
	exit 1
fi

# Check that we are not currently running a backupz operation.
ps aux | grep "backupz"  | grep -v "grep backupz"
if [ ${?} -eq 0 ]; then
	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\n       Aborting.\n"
	exit 1
fi

# Check that user exists.
grep -e "${USERNAME}" /etc/passwd > /dev/null
if [ ${?} -ne 0 ]; then
	echo -e "\n${LRED}ERROR:${NRML} User does not exists, please check username!\n       Aborting.\n"
	if [ "${FORCE_MODE}" !=  "yes" ]
	then
		exit 1
	fi
fi


##### MAIN EXECUTION THREAD ####################################################

ERROR_COUNT=0

# Destroy the hotdesk users' home directory filesystem.
echo -e "\n${YELL}Destroying the users' home filesystem...${NRML}\n"
zfs destroy -r -p -f ${HOME_ZFS_NAME}/${USERNAME}
if [ ${?} != 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} Hotdesk user home directory not destroyed, please verify username!\n       Aborting.\n"
	if [ "${FORCE_MODE}" !=  "yes" ]
	then
		exit 1
	fi
else
	echo -e "\n${YELL}Hotdesk user home folder destroyed.${NRML}\n"
	zfs list -H ${DEFAULT_BACKUP_POOL}/${HOME_ZFS_NAME}/${USERNAME} > /dev/null 2>&1
	if [ ${?} -eq 0 ]
	then
		echo -e "\n${YELL}Renaming backup filesystem for the users' home filesystem...\n"
		zfs rename -f ${DEFAULT_BACKUP_POOL}/${HOME_ZFS_NAME}/${USERNAME} ${DEFAULT_BACKUP_POOL}/${HOME_ZFS_NAME}/DESTROYED-${NOW}_${USERNAME} > /dev/null 2>&1
		if [ ${?} -eq 1 ]
		then
			echo -e "\n${LRED}ERROR:${NRML} An error occured trying to rename the filesystem:\n       ${DEFAULT_BACKUP_POOL}/${HOME_ZFS_NAME}/${USERNAME}\n"
		fi
	else
		echo -e "\n${ORNG}WARNING:${NRML} If backupz is in use for the hotdesk users' filesystem,\n         consider destroying or renaming it."
		echo -e "         (<backup_pool>/${HOME_ZFS_NAME}/${USERNAME})\n"
	fi
fi

echo -e "\n${YELL}Removing the user from the exports file...${NRML}\n"
sed -i "" "/${USERNAME} /d" /etc/exports

echo -e "\n${YELL}Restarting mountd...${NRML}\n"
service mountd reload

echo -e "\n${YELL}Removing the user from NIS...${NRML}\n"
cd /var/yp
sed -i "" "/${USERNAME}/d" master.passwd
make

echo -e "\n${YELL}Removing the user from system...${NRML}\n"
rmuser -y ${USERNAME}

echo -e "\n${LGRN}Operation complete!${NRML}\n"

if [ ${ERROR_COUNT} -gt 0 ]
then
	exit 2
fi

################################################################################
