#!/bin/sh

# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################

SCRIPT_NAME=`basename ${0}`
HOST_NAME="${1}"
HOST_IP="${2}"
NUM_MANDATORY_ARGS=2
IS_INTERACTIVE="yes"
DNS_CACHE_SERVER_FOUND="no"
FDO_SERVER_SCRIPT=${FDO_SERVER_SCRIPT:-"fdo-server"}
UCL_CMD="/usr/local/bin/uclcmd"
FDO_CONFIG_ROOT=${FDO_CONFIG_ROOT:-"/usr/local/etc/fdo"}
HOST_CONF_PATH=${HOST_CONF_PATH:-"${FDO_CONFIG_ROOT}/host.conf"}
REPO_NAME=${REPO_NAME:-"fdo-server"}

TERM="xterm"
LRED="\033[1;31m"
LGRN="\033[1;32m"
LBLU="\033[1;34m"
LCYN="\033[1;36m"
CYAN="\033[0;36m"
YELL="\033[1;33m"
ORNG="\033[0;33m"
GREY="\033[0;37m"
DGRY="\033[1;30m"
NRML="\033[0;00m"

CARRIAGE_RETURN="
"

##### COMMAND USAGE INFO #######################################################

usage ()
{
	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
	then
		return 1
	fi

	echo -e ""
	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
	echo -e ""
	echo -e "${YELL}Description:${NRML} Add hostname zone to FDo dns_cache jail services on this host."
	echo -e ""
	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} hostname ip_address [--non-interactive]${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} site1.example.net 10.0.11.20${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} site2.example.net 10.0.11.21 --non-interactive${NRML}"
	echo -e ""
	echo -e "${YELL}Options:${NRML}"
	echo -e "${YELL}         --non-interactive ; Will not prompt or commit changes to the config repo.${NRML}"
	echo -e ""
}


##### PARSE ARGUMENTS ##########################################################

ARG_INDEX=1
for ARG in "${@}"
do
	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
	then
		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
		case ${OPTIONAL_ARG_NAME} in
			--non-interactive)
				IS_INTERACTIVE="no"
				;;
			*)
				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\n       Aborting.\n"
				usage
				exit 1
				;;
		esac
	fi

	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))

done


##### FUNCTIONS ################################################################

# source readee function
. /usr/local/bin/fdo-readee

question_yes_no ()
{
	while true
	do
		echo -e "${LCYN}${1}${NRML}"
		readee -p "${LCYN}(yes|no): ${NRML}" ANSWER
		if [ "${ANSWER}" = "yes" ] || [ "${ANSWER}" = "no" ]
		then
			break
		fi
		echo ""
	done
}

test_valid_inet_address ()
{

	TEST_CASE="${1}"

	VALID_INET_ADDRESS="yes"

	if [ "${TEST_CASE}" = "" ]
	then
		VALID_INET_ADDRESS="no"
		return 1
	fi

	IS_SYNTAX_OK=`echo "${TEST_CASE}" | sed "s/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$//" | wc -L`
	if [ ${IS_SYNTAX_OK}  -ne 0 ]
	then
		VALID_INET_ADDRESS="no"
		return 2
	fi

	NO_ZEROS_IN_FRONT=`echo "${TEST_CASE}" | sed "s/\.0[0-9]//" | sed "s/^0//"`
	if [ "${NO_ZEROS_IN_FRONT}" != "${TEST_CASE}" ]
	then
		VALID_INET_ADDRESS="no"
		return 3
	fi

	ONE=`echo "${TEST_CASE}" | cut -d. -f1`
	TWO=`echo "${TEST_CASE}" | cut -d. -f2`
	THREE=`echo "${TEST_CASE}" | cut -d. -f3`
	FOUR=`echo "${TEST_CASE}" | cut -d. -f4`

	if [ ${ONE} -gt 255 ] || [ ${TWO} -gt 255 ] || [ ${THREE} -gt 255 ] || [ ${FOUR} -gt 255 ]
	then
		VALID_INET_ADDRESS="no"
		return 4
	fi

}

test_valid_fqhn ()
{

	TEST_CASE="${1}"

	VALID_FQHN="yes"

	if [ "${TEST_CASE}" = "" ]
	then
		VALID_FQHN="no"
		return 1
	fi

	IS_SYNTAX_OK=`echo "${TEST_CASE}" | sed -r "s/^((([a-zA-Z0-9]+[\-])*[a-zA-Z0-9]+)+\.)+[a-zA-Z0-9]+//" | wc -L`
	if [ ${IS_SYNTAX_OK}  -ne 0 ]
	then
		VALID_FQHN="no"
		return 2
	fi

}

test_if_host ()
{
	procstat 0 > /dev/null 2>&1
	if [ ${?} -eq 0 ]
	then
		IS_HOST=yes
	else
		IS_HOST=no
	fi
}

backup_file ()
{
	FILE_PATH="${1}"
	CHANGE_AGENT="${2}"
	if [ -f "${FILE_PATH}" ]
	then
		BACKUP_FILE_PATH="${FILE_PATH}.backup.${CHANGE_AGENT}"
		cp "${FILE_PATH}" "${BACKUP_FILE_PATH}" 2> /dev/null
		if [ ${?} -ne 0 ]
		then
			echo -e "\n${LRED}ERROR:${NRML} Failed to backup file '${ORNG}${FILE_PATH}${NRML}'!\n"
			BACKUP_FILE_PATH=""
			return 2
		fi
	else
		echo -e "\n${LRED}ERROR:${NRML} File '${ORNG}${FILE_PATH}${NRML}' does not exist!\n       Unable to backup.\n"
		BACKUP_FILE_PATH=""
		return 1
	fi

	return 0
}

restore_file ()
{
	FILE_PATH=${1}
	CHANGE_AGENT="${2}"

	if [ -f "${FILE_PATH}" ] && [ -f "${FILE_PATH}.backup.${CHANGE_AGENT}" ]
	then
		diff -q "${FILE_PATH}" "${FILE_PATH}.backup.${CHANGE_AGENT}" > /dev/null 2>&1
		if [ ${?} -ne 0 ]
		then
			# File and backup differ, replace the file content from the backup copy.
			cat "${FILE_PATH}.backup.${CHANGE_AGENT}" > "${FILE_PATH}"
			if [ ${?} -ne 0 ]
			then
				return 2
			fi
		fi
		# Remove the backup.
		rm "${FILE_PATH}.backup.${CHANGE_AGENT}"
		if [ ${?} -ne 0 ]
		then
			return 2
		fi
	else
		# File has been removed, so move backup to file path.
		mv "${FILE_PATH}.backup.${CHANGE_AGENT}" "${FILE_PATH}"
		if [ ${?} -ne 0 ]
		then
			return 2
		fi
	fi

	return 0

}

undo_backup_file ()
{
	FILE_PATH=${1}
	CHANGE_AGENT="${2}"

	if [ -f "${FILE_PATH}.backup.${CHANGE_AGENT}" ]
	then
		# Remove the backup.
		rm "${FILE_PATH}.backup.${CHANGE_AGENT}"
		if [ ${?} -ne 0 ]
		then
			return 2
		fi
	fi

	return 0

}

undo_add_hostname ()
{
	ERROR_COUNT=0

	echo -e "\n${ORNG}Undoing add hostname process...${NRML}\n"

	# Restore existing and delete newly created system config files.
	if [ ${ADD_HOSTNAME_SYSTEM_MODIFIED} = true ]
	then
		restore_file "${NAMED_CONF_PATH}" ${SCRIPT_NAME}
		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
		rm /jls/${JAIL_NAME}${ZONE_FILE_PATH}
		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
	fi

	# Reload bind (named) service.
	if [ ${ADD_HOSTNAME_BIND_RELOADED} = true ]
	then
		jexec ${JAIL_ID} service named reload > /dev/null
		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
	fi

	# Undo repo modifications.
	if [ ${ADD_HOSTNAME_REPO_MODIFIED} = true ]
	then
		# Roll back local repo to last good commit (!!!DANGEROUS!!!).
		if [ "${COMMIT_BEFORE_ADD_HOSTNAME}" != "" ]
		then
			git reset --hard ${COMMIT_BEFORE_ADD_HOSTNAME}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			git clean -f -d
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
		fi
	fi

	if [ ${ERROR_COUNT} -ne 0 ]
	then
		echo -e "\n${LRED}ERROR:${NRML} An error occurred whilst trying to undo add hostname!\n"
	else
		echo -e ""
	fi
}


##### SANITY TESTS #############################################################

if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
then
	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
	usage
	exit 1
fi

# Check we are running with root privileges.
if [ `id -u` -ne 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} This command must be run with root (super-user) privileges!\n       Aborting.\n"
	exit 1
fi

test_if_host

if [ "${IS_HOST}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
	exit 1
fi

# Check that the host.conf file exists.
if [ ! -e "${HOST_CONF_PATH}" ]
then
	echo -e "\n${LRED}ERROR:${NRML} The host config file \n       '${ORNG}${HOST_CONF_PATH}${NRML}'"
	echo -e "       appears to be missing.\n       Aborting.\n"
	exit 1
fi

# Check that the host.conf file is accessible.
TEST_UCL=`${UCL_CMD} get -u -f ${HOST_CONF_PATH} .general 2>&1`
if [ ${?} -ne 0 ] || [ "${TEST_UCL}" = "null" ] || [ "${TEST_UCL}" = "" ]
then
	echo -e "\n${LRED}ERROR:${NRML} Failed to access the config file '${HOST_CONF_PATH}'!\n       Aborting.\n"
	exit 2
fi

# Check for unsaved registered host config files.
echo -e "\n${YELL}Now we need to check if there are any unsaved changes to this hosts registered\nconfig files...${NRML}\n"
${FDO_SERVER_SCRIPT} check-configs --script > /dev/null 2>&1
if [ ${?} -gt 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} One or more host config files are not updated in the repo."
	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} check-configs${NRML}' subcommand to see what's out-of-date."
	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} update-config${NRML}' subcommannd to keep the repo up-to-date.\n       Aborting.\n"
	exit 1
fi

# Check that the hostname is valid.
test_valid_fqhn  "${HOST_NAME}"
if [ "${VALID_FQHN}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} The hostname '${ORNG}${HOST_NAME}${NRML}' is invalid!"
	echo -e "       It must only contain letters, numbers, periods and hyphens."
	echo -e "       It must not begin or end with a hyphen or a period."
	echo -e "       Aborting.\n"
	exit 1
fi

# Test if ip_address is valid
test_valid_inet_address "${HOST_IP}"
if [ "${VALID_INET_ADDRESS}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} IP address is invalid!"
	echo -e "       Aborting.\n"
	exit 1
fi


##### MAIN EXECUTION THREAD ####################################################

trap 'undo_add_hostname ; exit 3' HUP INT QUIT KILL TERM

ERROR_COUNT=0

ADD_HOSTNAME_BIND_RELOADED=false
ADD_HOSTNAME_REPO_MODIFIED=false
ADD_HOSTNAME_SYSTEM_MODIFIED=false

# Move into local repo directory.
cd "/${REPO_NAME}"
if [ ${?} -ne 0 ]
then
	echo -e "\n${LRED}ERROR:${NRML} Unable to enter the repo directory; '${ORNG}/${REPO_NAME}${NRML}'!"
	return 2
fi

# Save git commit reference so we can roll back changes later.
COMMIT_BEFORE_ADD_HOSTNAME=`git log --format=format:%H -1`

# Iterate through all jails...
for JAIL_NAME in `ls -1 /jls | cut -d/ -f1 | egrep -v "template"`
do
	NAMED_CONF_PATH="/jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf"
	ZONE_FILE_PATH="/usr/local/etc/namedb/primary/${HOST_NAME}.db"

	# ...and if a bind server exists...
	if [ -f "${NAMED_CONF_PATH}" ]
	then
		# ...determine if it's a caching server
		cat "${NAMED_CONF_PATH}" | egrep "^( )*forwarders {" > /dev/null 2>&1
		if [ ${?} -eq 0 ]
		then

			DNS_CACHE_SERVER_FOUND=yes

			# Now that we've found a caching server, let's see if the record already exists:
			cat "${NAMED_CONF_PATH}" | egrep "^zone \"${HOST_NAME}\"" > /dev/null 2>&1
			if [ ${?} -eq 0 ]
			then
				echo -e "\n${LRED}ERROR:${NRML} The record for hostname '${ORNG}${HOST_NAME}${NRML}' already exists!"
				echo -e "       Aborting.\n"
				exit 1
			fi

			# Since it does not already exist, let's add a zone for our new hostname record:

			# Backup affected system files in case something goes wrong.
			backup_file "${NAMED_CONF_PATH}" ${SCRIPT_NAME}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))

			ADD_HOSTNAME_SYSTEM_MODIFIED=true

			# - Add zone entry in named.conf
			echo "zone \"${HOST_NAME}\" { type primary; file \"${ZONE_FILE_PATH}\"; };" >> "${NAMED_CONF_PATH}"
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))

			# - Create the primary zone file
			DATE=`date "+%Y%m%d"`
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			echo "" > /jls/${JAIL_NAME}${ZONE_FILE_PATH}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			echo "\$TTL 3h" >> /jls/${JAIL_NAME}${ZONE_FILE_PATH}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			echo "@ SOA @ nobody.localhost. ${DATE}01 1d 12h 1w 3h ;" >> /jls/${JAIL_NAME}${ZONE_FILE_PATH}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			echo "                        ; Serial, Refresh, Retry, Expire, Neg. cache TTL" >> /jls/${JAIL_NAME}${ZONE_FILE_PATH}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			echo "" >> /jls/${JAIL_NAME}${ZONE_FILE_PATH}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			echo "        IN      NS      ${HOST_NAME}." >> /jls/${JAIL_NAME}${ZONE_FILE_PATH}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			echo "" >> /jls/${JAIL_NAME}${ZONE_FILE_PATH}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			echo "${HOST_NAME}.        A       ${HOST_IP}" >> /jls/${JAIL_NAME}${ZONE_FILE_PATH}
			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))

			if [ ${ERROR_COUNT} -ne 0 ]
			then
				echo -e "\n${LRED}ERROR:${NRML} An unexpected error occurred preparing the new configuration!\n       Aborting.\n"
				undo_add_hostname
				exit 2
			fi

			# - Reload bind server
			ADD_HOSTNAME_BIND_RELOADED=true
			JAIL_ID_FILE=`ls -1 /var/run/jail_${JAIL_NAME}.id | head -1`
			JAIL_ID=`cat ${JAIL_ID_FILE}`
			echo -e "\n${YELL}Reloading the named service...${NRML}\n"
			jexec ${JAIL_ID} service named reload > /dev/null
			if [ ${?} -ne 0 ]
			then
				echo -e "\n${ORNG}WARNING:${NRML} Failed to reload named (caching DNS) service in jail '${JAIL_NAME}'!\n"
			else
				echo -e "${YELL}INFO:${NRML} Successfully updated named (caching DNS) service in jail '${YELL}${JAIL_NAME}${NRML}'!\n"
			fi

			# Update configuration in the local repo and if interactive mode then push to remote repo
			ADD_HOSTNAME_REPO_MODIFIED=true
			if [ "${IS_INTERACTIVE}" = "yes" ]
			then
				echo -e "\n${FDO_SERVER_SCRIPT} update-config ${NAMED_CONF_PATH} ...\n"
				CHANGE_MESSAGE="add hostname '${HOST_NAME}' to caching DNS" GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config "${NAMED_CONF_PATH}"
				ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
				echo -e "\n${FDO_SERVER_SCRIPT} add-config /jls/${JAIL_NAME}${ZONE_FILE_PATH} ...\n"
				FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} add-config "/jls/${JAIL_NAME}${ZONE_FILE_PATH}"
				ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			else
				echo -e "\n${FDO_SERVER_SCRIPT} update-config ${NAMED_CONF_PATH} ...\n"
				CHANGE_MESSAGE="add hostname '${HOST_NAME}' to caching DNS" GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config "${NAMED_CONF_PATH}"
				ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
				echo -e "\n${FDO_SERVER_SCRIPT} add-config /jls/${JAIL_NAME}${ZONE_FILE_PATH} ...\n"
				GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} add-config "/jls/${JAIL_NAME}${ZONE_FILE_PATH}"
				ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
			fi

			if [ ${ERROR_COUNT} -ne 0 ]
			then
				echo -e "\n${LRED}ERROR:${NRML} Something went wrong whilst commiting changes to the configs repo!\n       Aborting.\n"
				undo_add_hostname
				exit 2
			fi

			undo_backup_file "${NAMED_CONF_PATH}" ${SCRIPT_NAME}

			break
		fi
	fi
done

if [ "${DNS_CACHE_SERVER_FOUND}" = "no" ]
then
	echo -e "\n${LRED}ERROR:${NRML} No caching dns server found!\n       Aborting.\n"
	exit 1
fi

echo -e ""

################################################################################
