#!/bin/sh

# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY 
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY 
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


SCRIPT_NAME=`basename $0`

LRED="\033[1;31m"
LGRN="\033[1;32m"
LBLU="\033[1;34m"
LCYN="\033[1;36m"
YELL="\033[1;33m"
ORNG="\033[0;33m"
NRML="\033[0;00m"

CARRIAGE_RETURN="
"

usage (){
  echo -e ""
  echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME}${NRML}"
  echo -e ""
}

if [ $# -ne 0 ]
then
  usage
  exit 1
fi

EXCLUDED_ZONES=".arpa\"|\"localhost\"|\"test\"|\"example\"|\"invalid\"|\"example.com\"|\"example.net\"|\"example.org\"|\"ip6.int\"|\"\.\""
DNS_CACHE_SERVER_FOUND="no"

# Iterate through all jails...
for JAIL_NAME in `ls -1 /jls | cut -d/ -f1 | egrep -v "template"`
do
  # ...and if a bind server exists...
  if [ -f "/jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf" ]
  then
    # ...determine if it's a caching server
    cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^( )*forwarders {" > /dev/null 2>&1
    if [ ${?} -eq 0 ] 
    then

      DNS_CACHE_SERVER_FOUND=yes
      # Now that we've found a caching server, let's list the hostname zones:
      cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^zone \"" | egrep -v ${EXCLUDED_ZONES} | cut -d'"' -f2

    fi
  fi
done

if [ "${DNS_CACHE_SERVER_FOUND}" = "no" ]
then
  exit 1
fi
