#!/bin/sh

if [ $# -lt 2 ]
then
  echo "Usage:   $0 pool_to_destroy_from snapshot_pattern [OPTION]..."
  echo "Example: $0 backup Accounts@2013"
  echo ""
  echo ""
  echo "Options:"
  echo ""
  echo "-s, --simulate          simulation mode, will output the command but execute them."
  echo ""
  exit 1
fi

POOL=$1
SNAPSHOT_PATTERN=$2

for i in ${@}
do
  case ${i} in
  -s) SIMULATION="true"
      ;;
  --simulate) SIMULATION="true"
      ;;
  esac
done

TO_DESTROY=`zfs list -t snapshot -r ${POOL} | grep "${SNAPSHOT_PATTERN}" | cut -d " " -f 1`
if [ "${SIMULATION}" = "true" ]
then
  echo ""
  echo "!!! SIMULATION Mode !!!"
  echo ""
  echo ""
  for i in ${TO_DESTROY} ; do echo "zfs destroy -v ${i}" ; done
else
  echo ""
  echo "Destroying snapshot starts!"
  echo ""
  for i in ${TO_DESTROY} ; do zfs destroy -v ${i} ; done
fi
