#!/bin/sh

# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################

SCRIPT_NAME=`basename ${0}`
JAIL_SEARCH_STRING="${1}"
NUM_MANDATORY_ARGS=1
LOGIN_SHELL=""

CURRENT_TERM="${TERM}"
TERM="xterm"
LRED="\033[1;31m"
LGRN="\033[1;32m"
LBLU="\033[1;34m"
LCYN="\033[1;36m"
CYAN="\033[0;36m"
YELL="\033[1;33m"
ORNG="\033[0;33m"
GREY="\033[0;37m"
DGRY="\033[1;30m"
NRML="\033[0;00m"

CARRIAGE_RETURN="
"

##### COMMAND USAGE INFO #######################################################

usage ()
{
	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
	then
		return 1
	fi

	echo -e ""
	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
	echo -e ""
	echo -e "${YELL}Description:${NRML} Login to a shell inside a jail."
	echo -e ""
	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} jail_name [--shell=\"value\"]${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} ldap${NRML}"
	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} files --shell=\"/bin/csh\"${NRML}"
	echo -e ""
	echo -e "${YELL}Options:${NRML}"
	echo -e ""
	echo -e "${YELL}--shell  Specify the login shell (full path).${NRML}"
	echo -e ""
}


##### PARSE ARGUMENTS ##########################################################

ARG_INDEX=1
for ARG in "${@}"
do
	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
	then
		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
		case ${OPTIONAL_ARG_NAME} in
			--shell)
				LOGIN_SHELL="${OPTIONAL_ARG_VALUE}"
				;;
			*)
				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\n       Aborting.\n"
				usage
				exit 1
				;;
		esac
	fi

	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))

done


##### SANITY TESTS #############################################################

if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
then
	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
	usage
	exit 1
fi


##### FUNCTIONS ################################################################



################################################################################


##### MAIN EXECUTION THREAD ####################################################

ERROR_COUNT=0

# Get the jail name and jid file name of closest match
JID_FILES=`ls -1 /var/run/jail_*.id | grep -- "${JAIL_SEARCH_STRING}"`

JAIL_NAME=""
JAIL_NAME_REMAINDER=0

for JID_FILE_CANDIDATE in ${JID_FILES}
do
	JAIL_NAME_CANDIDATE=`echo "${JID_FILE_CANDIDATE}" | sed "s|/var/run/jail_\(.*\).id|\1|"`
	CANDIDATE_REMAINDER=`echo "${JAIL_NAME_CANDIDATE}" | sed "s|${JAIL_SEARCH_STRING}||" | wc -c`
	if [ "${JAIL_NAME}" = "" ]
	then
		JAIL_NAME="${JAIL_NAME_CANDIDATE}"
		JID_FILE="${JID_FILE_CANDIDATE}"
		JAIL_NAME_REMAINDER=${CANDIDATE_REMAINDER}
	else
		if [ ${CANDIDATE_REMAINDER} -lt ${JAIL_NAME_REMAINDER} ]
		then
			JAIL_NAME="${JAIL_NAME_CANDIDATE}"
			JID_FILE="${JID_FILE_CANDIDATE}"
			JAIL_NAME_REMAINDER=${CANDIDATE_REMAINDER}
		fi
	fi
done

# If nothing found, inform user and exit
if [ "${JAIL_NAME}" = "" ]
then
	echo -e "\n${LRED}ERROR:${NRML} No jail found matching '${JAIL_SEARCH_STRING}'!\n       Aborting.\n"
	usage
	exit 1
fi

JID=`cat ${JID_FILE}`

if [ "${JID}" = "" ]
then
	echo -e "\n${LRED}ERROR:${NRML} No jid found in '${JID_FILE}'!\n       Aborting.\n"
	usage
	exit 1
fi

echo -e "\n${YELL}Logging in to ${JAIL_NAME}...${NRML}\n"

TERM="${CURRENT_TERM}"

if [ "${LOGIN_SHELL}" = "" ]
then
	jexec ${JID}
else
	jexec ${JID} ${LOGIN_SHELL}
fi

if [ ${ERROR_COUNT} -gt 0 ]
then
	exit 2
fi

################################################################################
