#!/bin/sh

#### Recipe Variable Definitions ###############################################
JAIL_IP="${JAILS_LAN_SUBNET_C}.30"                                             # Optional:  ip address given to the jail (see FDo IP Policy)
RECIPE_PACKAGES="nginx"                                                        # Optional:  packages to install in the jail
RECIPE_REQUIRES_JAIL_RESTART="no"                                              # Mandatory: set to "yes" if the jail requires a restart after cooking
RECIPE_REQUIRES_NAT_RELOAD="yes"                                               # Mandatory: set to "yes" if the hosts NAT (pf/ppp) requires a restart after cooking
RECIPE_TCP_PORTS="80,443"                                                      # Optional:  tcp ports to forward, necessary for port forwarding
RECIPE_UDP_PORTS="none"                                                        # Optional:  udp ports to forward, necessary for port forwarding
START_JAIL_SERVICES="nginx"                                                    # Optional:  jail services started after cooking (in left to right order)
RECIPE_ZFS_DATASETS=""                                                         # Optional:  name of extra ZFS datasets required for recipe
RECIPE_ZFS_MOUNTPOINTS=""                                                      # Optional:  mountpoint of extra ZFS datasets required for recipe
################################################################################

seasoning_suggestions ()
{

	echo -e "\n${ORNG}NOTICE:${NRML} The upstream web host config files should be placed in the path:       \n"
	echo -e   "        /usr/local/etc/nginx/sites                                              \n"


}

cook_recipe ()
{

	echo -e "\n${YELL}Next we need to install the recipe packages into the jail."
	echo -e "Please accept when prompted...${NRML}\n"
	sleep 5

	# Install essential jail recipe packages from the recipe repo
	pkg -j ${JAIL_NAME} install ${RECIPE_PACKAGES}
	if [ ${?} -ne 0 ]
	then
		echo -e "\n${LRED}ERROR:${NRML} Installing of recipe packages failed.\n"
		RECIPE_SUCCESS="no"
		return
	fi

	## TODO: ask for number of worker processes
	WORKER_PROCESSES=`sysctl hw.ncpu | awk '{print $2}'`

	# Replace variables in nginx.conf file
	sed -i "" "s/WORKER_PROCESSES/${WORKER_PROCESSES}/" configs/${JAIL_NAME}@${HOST_NAME}/usr/local/etc/nginx/nginx.conf

	# Replace variables in hosts file
	sed -i "" "s/JAIL_IP/${JAIL_IP}/" configs/${JAIL_NAME}@${HOST_NAME}/etc/hosts
	sed -i "" "s/JAIL_HOST_NAME/${JAIL_HOST_NAME}/" configs/${JAIL_NAME}@${HOST_NAME}/etc/hosts

	seasoning_suggestions
	seasoning_suggestions > /jls/${JAIL_NAME}/.fdo-post-cooking-steps.inf

	# Mandatory: return code
	RECIPE_SUCCESS="yes"

}
